[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/RonPlusSign/AnomalySegmentation/blob/chris-1/Project6.ipynb)

# **Anomaly Segmentation Project 6**
##*Andrea Delli, Christian Dellisanti, Giorgia Modi*

###**Dataset Preparation**

In [52]:

!pip  install -q numpy matplotlib Pillow torchvision visdom ood_metrics

import sys, os
if not os.path.isfile('/content/Validation_Dataset.zip'):
  !gdown 12YJq48XkCxQHjN3CmLc-zM5dThSak4Ta
if not os.path.isdir('/content/Validation_Dataset'):
  !unzip Validation_Dataset.zip
if not os.path.isdir('/content/AnomalySegmentation'):
  #!git clone https://github.com/shyam671/AnomalySegmentation_CourseProjectBaseCode.git
  #token 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
  !git clone -b chris-1 https://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@github.com/RonPlusSign/AnomalySegmentation.git
!cd /content/AnomalySegmentation && git pull

remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 4 (delta 3), reused 4 (delta 3), pack-reused 0 (from 0)
Unpacking objects: 100% (4/4), 345 bytes | 172.00 KiB/s, done.
From https://github.com/RonPlusSign/AnomalySegmentation
   0caa8c0..8e13659  chris-1    -> origin/chris-1
Updating 0caa8c0..8e13659
Fast-forward
 eval/evalAnomaly.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)


###**Anomaly Inference**

In [54]:
import torch
# se vado alla linea 87 di evalAnomaly.py quello dovrebbe essere l'utilizzo di MSP

for dataset_dir in ['RoadAnomaly', 'FS_LostFound_full', 'RoadObsticle21', 'RoadAnomaly21', 'fs_static']:
  if not torch.cuda.is_available():
    for method in ["MSP", "MaxLogit", "MaxEntropy"]: #MaxEntropy in the future

      format_file = os.listdir(f'/content/Validation_Dataset/{dataset_dir}/images')[0].split(".")[1]
      input =f'/content/Validation_Dataset/{dataset_dir}/images/*.{format_file}'
      print(f"\nDataset: {dataset_dir} method : {method}")
      !python -W ignore /content/AnomalySegmentation/eval/evalAnomaly.py --input {input} --loadDir '/content/AnomalySegmentation/trained_models/' --method {method} --cpu
      break
    break


Dataset: RoadAnomaly method : MSP
Loading model: /content/AnomalySegmentation/trained_models/erfnet.py
Loading weights: /content/AnomalySegmentation/trained_models/erfnet_pretrained.pth
Model and weights LOADED successfully
/content/Validation_Dataset/RoadAnomaly/images/0.jpg
result.shpe torch.Size([1, 20, 720, 1280])
result.squeeze(0).data.cpu().numpy() : 921599.8125
ood_gts appena caricato : [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
val_out : [2.3841858e-07 4.7683716e-07 1.2464023e-01 ... 2.9829204e-02 2.3841858e-06
 1.1920929e-07] 
 val_label : [0. 0. 0. ... 1. 1. 1.]
AUPRC score: 6.73843136602053
FPR@TPR95: 94.89165173912563


##**Temperature Scaling**

**Anomaly Inference with temperature**

In [44]:
import torch



for t in [0.5, 0.75, 1.1]:
  for dataset_dir in ['RoadAnomaly', 'FS_LostFound_full', 'RoadObsticle21', 'RoadAnomaly21', 'fs_static']:

    format_file = os.listdir(f'/content/Validation_Dataset/{dataset_dir}/images')[0].split(".")[1]
    input =f'/content/Validation_Dataset/{dataset_dir}/images/*.{format_file}'
    print(f"\nDataset: {dataset_dir} method : MSP Temperature: {t}")

    !python -W ignore /content/AnomalySegmentation/eval/evalAnomaly.py --input {input} --loadDir '/content/AnomalySegmentation/trained_models/'  --method 'MSP'  --cpu  --temperature {t} | tail -n 2




Dataset: RoadAnomaly method : MSP Temperature: 0.5
AUPRC score: 6.711344253191805
FPR@TPR95: 94.9778651262153

Dataset: FS_LostFound_full method : MSP Temperature: 0.5
AUPRC score: 0.046513549713061375
FPR@TPR95: 96.1368579659756

Dataset: RoadObsticle21 method : MSP Temperature: 0.5
AUPRC score: 0.018794117004305163
FPR@TPR95: 95.20898177939428

Dataset: RoadAnomaly21 method : MSP Temperature: 0.5
AUPRC score: 1.662199319412507
FPR@TPR95: 95.1301177602757

Dataset: fs_static method : MSP Temperature: 0.5
AUPRC score: 2.779911842973269
FPR@TPR95: 95.46371734399979

Dataset: RoadAnomaly method : MSP Temperature: 0.75
AUPRC score: 6.723575093120552
FPR@TPR95: 94.93579185596369

Dataset: FS_LostFound_full method : MSP Temperature: 0.75
AUPRC score: 0.044913449681561586
FPR@TPR95: 96.6792729040551

Dataset: RoadObsticle21 method : MSP Temperature: 0.75
AUPRC score: 0.018794117004305163
FPR@TPR95: 95.305352521508

Dataset: RoadAnomaly21 method : MSP Temperature: 0.75
AUPRC score: 1.6463917

**DATASET MANAGEMENT** **TUTTO INUTILE GIÀ TUTTO SCRITTO**

In [ ]:
from torch.utils.data import Dataset
import os

from PIL import Image
import sys


def pil_loader(path):
    # open path as file to avoid ResourceWarning (https://github.com/python-pillow/Pillow/issues/835)
    with open(f"/content/Validation_Dataset/{path}", 'rb') as f:
        img = Image.open(f)
        return img.convert('RGB')


# Define the Dataset class
class PACSDataset(Dataset):
    def __init__(self, root= "/content/Validation_Dataset", source_domain="FS_LostFound_full" , dataset_transform=None):
      super(PACSDataset, self).__init__( )

      self.dataset_transform = dataset_transform

      self.root=f"{root}/{source_domain}"
      self.data   = os.listdir(f"{root}/{source_domain}/images")
      #self.labels = os.listdir(f"{root}/{source_domain}/labels_masks")



    def __len__(self):
        return len(self.data)

    def __getitem__(self, index):

      image, label = pil_loader(f"images/{self.data[index]}"), pil_loader(f"labels_masks/{self.data[index]}")

      # Applies preprocessing when accessing the image
      if self.dataset_transform is not None:
          image = self.dataset_transform(image)

      return image, label






**ARCHITECTURE SETUP**

In [ ]:
import torch.nn as nn

# Define AlexNet architecture class
class ErfNet(nn.Module):
    def __init__(self, num_classes=1000):
        super(AlexNet, self).__init__()
        self.features = nn.Sequential(
            nn.Conv2d(3, 64, kernel_size=11, stride=4, padding=2),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=3, stride=2),
            nn.Conv2d(64, 192, kernel_size=5, padding=2),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=3, stride=2),
            nn.Conv2d(192, 384, kernel_size=3, padding=1),
            nn.ReLU(inplace=True),
            nn.Conv2d(384, 256, kernel_size=3, padding=1),
            nn.ReLU(inplace=True),
            nn.Conv2d(256, 256, kernel_size=3, padding=1),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=3, stride=2)
        )
        # Category classifier
        self.classifier = nn.Sequential(
            nn.Dropout(),
            nn.Linear(256 * 6 * 6, 4096),
            nn.ReLU(inplace=True),
            nn.Dropout(),
            nn.Linear(4096, 4096),
            nn.ReLU(inplace=True),
            nn.Linear(4096, num_classes)
        )
        # Domain classifier
        self.domain_classifier = nn.Sequential(
            nn.Dropout(),
            nn.Linear(256 * 6 * 6, 4096),
            nn.ReLU(inplace=True),
            nn.Dropout(),
            nn.Linear(4096, 4096),
            nn.ReLU(inplace=True),
            nn.Linear(4096, 2)
        )

    def forward(self, x):
        features = self.features(x)
        features = features.view(features.size(0), -1)
        class_outputs = self.classifier(features)
        domain_outputs = self.domain_classifier(features)
        return class_outputs, domain_outputs